.pragma library
// Emoji for the picker (Super+.): the emoji, English words, Russian words. The common ones, in the
// order people reach for them; the Noto Color Emoji font draws them (fonts-noto-color-emoji).
// SPDX-License-Identifier: Apache-2.0

var list = [
    ["😀", "grinning smile happy", "улыбка радость смех"],
    ["😂", "joy tears laugh lol", "смех до слёз ржу лол"],
    ["🤣", "rofl rolling laugh", "катаюсь от смеха ржака"],
    ["😊", "blush smile happy", "улыбка смущение радость"],
    ["😍", "heart eyes love", "влюблён сердечки любовь"],
    ["🥰", "love hearts adore", "любовь обожаю нежность"],
    ["😘", "kiss love", "поцелуй чмок"],
    ["😉", "wink", "подмигивание подмигнуть"],
    ["😎", "cool sunglasses", "круто очки крутой"],
    ["🤔", "thinking hmm", "думаю хм размышляю"],
    ["🙂", "slight smile", "лёгкая улыбка"],
    ["🙃", "upside down irony", "перевёрнутый ирония"],
    ["😅", "sweat smile phew", "уф неловко пот"],
    ["😆", "laughing squint", "хохот смеюсь"],
    ["😁", "beaming grin", "широкая улыбка скалюсь"],
    ["😇", "angel innocent halo", "ангел невинный"],
    ["🤩", "star struck wow", "восторг звёзды вау"],
    ["🥳", "party celebrate", "праздник вечеринка ура"],
    ["😏", "smirk", "ухмылка"],
    ["😌", "relieved calm", "облегчение спокойно"],
    ["😴", "sleeping tired", "сплю сон устал"],
    ["🥱", "yawn bored", "зеваю скучно"],
    ["😐", "neutral meh", "нейтрально пофиг"],
    ["😑", "expressionless", "без эмоций"],
    ["🙄", "eye roll", "закатываю глаза"],
    ["😬", "grimace awkward", "неловко гримаса"],
    ["😢", "cry sad tear", "плачу грусть слеза"],
    ["😭", "sob crying", "рыдаю плачу"],
    ["😔", "pensive sad", "грустно печаль"],
    ["😞", "disappointed", "разочарован"],
    ["😟", "worried", "беспокоюсь волнуюсь"],
    ["😤", "huff triumph", "фыркаю злюсь"],
    ["😠", "angry", "злой сержусь"],
    ["😡", "rage furious", "ярость бешенство"],
    ["🤯", "mind blown", "взрыв мозга шок"],
    ["😱", "scream fear shock", "крик ужас шок"],
    ["😨", "fearful scared", "страшно испуг"],
    ["😳", "flushed embarrassed", "смущён покраснел"],
    ["🥺", "pleading puppy eyes", "умоляю щенячьи глаза"],
    ["🤗", "hug", "обнимаю объятия"],
    ["🤭", "oops giggle", "упс хихикаю"],
    ["🤫", "shush quiet", "тихо тсс секрет"],
    ["🤐", "zipper mouth secret", "молчу рот на замке"],
    ["🤓", "nerd glasses", "ботан очкарик"],
    ["🧐", "monocle inspect", "монокль изучаю"],
    ["😷", "mask sick", "маска болею"],
    ["🤒", "thermometer ill", "температура болею"],
    ["🤢", "nauseated sick", "тошнит"],
    ["🤮", "vomit", "тошнит рвота"],
    ["🥵", "hot sweat", "жарко"],
    ["🥶", "cold freezing", "холодно мёрзну"],
    ["😵", "dizzy", "голова кружится"],
    ["🤠", "cowboy", "ковбой"],
    ["🤡", "clown", "клоун"],
    ["💀", "skull dead lol", "череп умер со смеху"],
    ["👻", "ghost", "призрак привидение"],
    ["👽", "alien", "инопланетянин пришелец"],
    ["🤖", "robot bot", "робот бот"],
    ["💩", "poop", "какашка"],
    ["😈", "devil smile", "чертёнок дьявол"],
    ["👍", "thumbs up like ok yes", "лайк класс да ок палец вверх"],
    ["👎", "thumbs down dislike no", "дизлайк нет палец вниз"],
    ["👌", "ok perfect", "окей отлично"],
    ["✌️", "victory peace", "победа мир"],
    ["🤞", "fingers crossed luck", "скрестил пальцы удачи"],
    ["🤝", "handshake deal", "рукопожатие договорились сделка"],
    ["👏", "clap applause", "аплодисменты хлопаю браво"],
    ["🙌", "raised hands hooray", "ура руки вверх"],
    ["🙏", "pray please thanks", "пожалуйста спасибо молюсь"],
    ["👋", "wave hello bye", "привет пока машу"],
    ["🤙", "call me shaka", "позвони созвон"],
    ["💪", "muscle strong", "сила мышцы качок"],
    ["👀", "eyes look", "глаза смотрю"],
    ["🧠", "brain smart", "мозг умный"],
    ["👉", "point right", "указываю вправо"],
    ["👈", "point left", "указываю влево"],
    ["👆", "point up", "указываю вверх"],
    ["👇", "point down", "указываю вниз"],
    ["✍️", "writing", "пишу"],
    ["🤷", "shrug dunno", "пожимаю плечами не знаю"],
    ["🤦", "facepalm", "фейспалм рукалицо"],
    ["🙋", "raising hand me", "я руку поднял"],
    ["❤️", "red heart love", "сердце любовь красное"],
    ["🧡", "orange heart", "оранжевое сердце"],
    ["💛", "yellow heart", "жёлтое сердце"],
    ["💚", "green heart", "зелёное сердце"],
    ["💙", "blue heart", "синее сердце"],
    ["💜", "purple heart", "фиолетовое сердце"],
    ["🖤", "black heart", "чёрное сердце"],
    ["🤍", "white heart", "белое сердце"],
    ["💔", "broken heart", "разбитое сердце"],
    ["💕", "two hearts", "сердечки"],
    ["💯", "hundred perfect", "сто процентов идеально"],
    ["🔥", "fire lit hot", "огонь жара круто"],
    ["✨", "sparkles magic", "блёстки магия"],
    ["⭐", "star", "звезда"],
    ["🌟", "glowing star", "сияющая звезда"],
    ["⚡", "lightning zap", "молния заряд"],
    ["💥", "boom collision", "бум взрыв"],
    ["🎉", "tada party", "праздник хлопушка поздравляю"],
    ["🎊", "confetti", "конфетти"],
    ["🎁", "gift present", "подарок"],
    ["🎂", "birthday cake", "торт день рождения"],
    ["🎈", "balloon", "шарик"],
    ["🏆", "trophy win", "кубок победа"],
    ["🥇", "gold medal first", "золото первое место медаль"],
    ["✅", "check done yes", "галочка готово да"],
    ["❌", "cross no wrong", "крестик нет ошибка"],
    ["⚠️", "warning", "внимание осторожно"],
    ["❗", "exclamation", "восклицательный важно"],
    ["❓", "question", "вопрос"],
    ["💡", "idea bulb", "идея лампочка"],
    ["📌", "pin", "булавка закрепить"],
    ["📎", "paperclip attach", "скрепка вложение"],
    ["🔗", "link", "ссылка"],
    ["🔒", "lock secure", "замок закрыто"],
    ["🔑", "key", "ключ"],
    ["⏰", "alarm clock", "будильник"],
    ["⏳", "hourglass wait", "песочные часы жду"],
    ["📅", "calendar date", "календарь дата"],
    ["📝", "memo note", "заметка записка"],
    ["📚", "books study", "книги учёба"],
    ["✏️", "pencil", "карандаш"],
    ["💻", "laptop computer", "ноутбук компьютер"],
    ["🖥️", "desktop computer", "компьютер монитор"],
    ["⌨️", "keyboard", "клавиатура"],
    ["🖱️", "mouse", "мышка мышь"],
    ["📱", "phone mobile", "телефон смартфон"],
    ["🎧", "headphones music", "наушники"],
    ["🎮", "game controller gaming", "игры геймпад играть"],
    ["🕹️", "joystick", "джойстик"],
    ["📷", "camera photo", "фотоаппарат фото"],
    ["🎬", "clapper movie", "кино фильм"],
    ["🎵", "music note", "музыка нота"],
    ["🎤", "microphone sing", "микрофон петь"],
    ["📦", "package box", "посылка коробка"],
    ["🛒", "cart shopping", "корзина покупки"],
    ["💰", "money bag", "деньги мешок"],
    ["💸", "money flying", "деньги улетают траты"],
    ["💳", "credit card", "карта банковская"],
    ["📈", "chart up growth", "рост график"],
    ["📉", "chart down", "падение график"],
    ["📊", "bar chart", "диаграмма"],
    ["🚀", "rocket launch", "ракета запуск"],
    ["✈️", "airplane travel", "самолёт путешествие"],
    ["🚗", "car", "машина авто"],
    ["🚌", "bus", "автобус"],
    ["🚲", "bicycle", "велосипед"],
    ["🏠", "house home", "дом"],
    ["🏢", "office building", "офис здание"],
    ["🏖️", "beach vacation", "пляж отпуск"],
    ["⛰️", "mountain", "гора"],
    ["🌍", "earth world", "земля мир планета"],
    ["☀️", "sun sunny", "солнце"],
    ["🌙", "moon night", "луна ночь"],
    ["⛅", "cloudy", "облачно"],
    ["🌧️", "rain", "дождь"],
    ["❄️", "snow cold", "снег снежинка"],
    ["🌈", "rainbow", "радуга"],
    ["🌸", "blossom flower", "цветок сакура"],
    ["🌹", "rose", "роза"],
    ["🌻", "sunflower", "подсолнух"],
    ["🌲", "tree pine", "ёлка дерево"],
    ["🍀", "clover luck", "клевер удача"],
    ["🐶", "dog puppy", "собака пёс щенок"],
    ["🐱", "cat kitty", "кот кошка котик"],
    ["🐭", "mouse", "мышь"],
    ["🦊", "fox", "лиса"],
    ["🐻", "bear", "медведь"],
    ["🐼", "panda", "панда"],
    ["🐯", "tiger", "тигр"],
    ["🦁", "lion", "лев"],
    ["🐸", "frog", "лягушка"],
    ["🐵", "monkey", "обезьяна"],
    ["🐔", "chicken", "курица"],
    ["🐧", "penguin", "пингвин"],
    ["🦄", "unicorn", "единорог"],
    ["🐝", "bee", "пчела"],
    ["🐢", "turtle slow", "черепаха медленно"],
    ["🐍", "snake python", "змея питон"],
    ["🐙", "octopus", "осьминог"],
    ["🐬", "dolphin", "дельфин"],
    ["🐳", "whale", "кит"],
    ["🦈", "shark", "акула"],
    ["🍎", "apple", "яблоко"],
    ["🍌", "banana", "банан"],
    ["🍓", "strawberry", "клубника"],
    ["🍉", "watermelon", "арбуз"],
    ["🍋", "lemon", "лимон"],
    ["🥑", "avocado", "авокадо"],
    ["🍕", "pizza", "пицца"],
    ["🍔", "burger", "бургер"],
    ["🍟", "fries", "картошка фри"],
    ["🌭", "hot dog", "хот-дог"],
    ["🌮", "taco", "тако"],
    ["🍣", "sushi", "суши"],
    ["🍜", "noodles ramen", "лапша рамен"],
    ["🥗", "salad", "салат"],
    ["🍰", "cake", "торт пирожное"],
    ["🍩", "donut", "пончик"],
    ["🍫", "chocolate", "шоколад"],
    ["🍿", "popcorn", "попкорн"],
    ["☕", "coffee", "кофе"],
    ["🍵", "tea", "чай"],
    ["🍺", "beer", "пиво"],
    ["🍷", "wine", "вино"],
    ["🥂", "cheers toast", "тост за нас бокалы"],
    ["⚽", "soccer football", "футбол мяч"],
    ["🏀", "basketball", "баскетбол"],
    ["🎾", "tennis", "теннис"],
    ["🏋️", "gym weights", "качалка спортзал"],
    ["🏃", "running", "бег бегу"],
    ["🧘", "yoga meditation", "йога медитация"],
    ["🎯", "target goal", "цель мишень"],
    ["🎲", "dice", "кубик игра"],
    ["♟️", "chess", "шахматы"],
    ["🧩", "puzzle", "пазл"],
    ["🛠️", "tools", "инструменты"],
    ["⚙️", "gear settings", "шестерёнка настройки"],
    ["🔧", "wrench fix", "гаечный ключ починить"],
    ["🧪", "test tube experiment", "пробирка эксперимент"],
    ["🔬", "microscope science", "микроскоп наука"],
    ["🧲", "magnet", "магнит"],
    ["🔋", "battery", "батарея"],
    ["🔌", "plug", "вилка розетка"],
    ["📡", "satellite antenna", "антенна связь"],
    ["🛰️", "satellite", "спутник"],
    ["🆘", "sos help", "сос помощь"],
    ["➡️", "right arrow", "стрелка вправо"],
    ["⬅️", "left arrow", "стрелка влево"],
    ["⬆️", "up arrow", "стрелка вверх"],
    ["⬇️", "down arrow", "стрелка вниз"],
    ["🔄", "repeat refresh", "обновить повтор"],
    ["➕", "plus", "плюс"],
    ["➖", "minus", "минус"],
    ["💬", "speech chat", "сообщение чат"],
    ["📢", "announcement", "объявление громко"],
    ["🔔", "bell notification", "колокольчик уведомление"],
    ["🔇", "mute", "без звука"],
    ["🇷🇺", "russia flag", "россия флаг"],
    ["🇪🇪", "estonia flag", "эстония флаг"],
    ["🇺🇦", "ukraine flag", "украина флаг"],
    ["🇬🇧", "uk britain flag", "британия англия флаг"],
    ["🇺🇸", "usa america flag", "сша америка флаг"],
    ["🇩🇪", "germany flag", "германия флаг"]
];

// words of the query all found in the emoji's words (each as the start of a word)
function matches(entry, query) {
    var words = String(query).toLowerCase().replace(/ё/g, "е").split(/\s+/).filter(function (w) { return w.length > 0; });
    if (words.length === 0)
        return true;
    var hay = " " + (entry[1] + " " + entry[2]).toLowerCase().replace(/ё/g, "е");
    for (var i = 0; i < words.length; i++) {
        if (hay.indexOf(" " + words[i]) < 0)
            return false;
    }
    return true;
}

function search(query) {
    return list.filter(function (e) { return matches(e, query); });
}
