#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Stage jackson/ into the package layout of ARCHITECTURE §3:
#   jackson/jackson          -> /usr/lib/svoya/jackson       (Python package)
#   jackson/bin/jackson      -> /usr/bin/jackson (+ /usr/bin/j)  (generated if missing)
#   jackson/bin/jacksond     -> /usr/lib/svoya/jacksond          (generated if missing)
#   jackson/systemd/*.service -> /usr/lib/systemd/user/          (default unit if missing)
#   jackson/skills/*/SKILL.md -> /usr/share/svoya/jackson/skills/  (system skills: sos, games)
set -euo pipefail
: "${SVOYA_SRC:?}" "${PKG_DIR:?}"
src=$SVOYA_SRC/jackson
files=$PKG_DIR/files
mkdir -p "$files/usr/bin" "$files/usr/lib/svoya" "$files/usr/lib/systemd/user"

python3 "$SVOYA_SRC/packages/lib/stage_pyapp.py" --src "$src" --package jackson --dest "$files" >/dev/null

wrapper() { # MODULE DEST
    cat >"$2" <<PY
#!/usr/bin/python3 -I
# Generated by packages/svoya-jackson/prepare.sh. SPDX-License-Identifier: Apache-2.0
import runpy
import sys

sys.path.insert(0, "/usr/lib/svoya")
runpy.run_module("$1", run_name="__main__", alter_sys=True)
PY
}

if [ -f "$src/bin/jackson" ]; then
    install -m 0755 "$src/bin/jackson" "$files/usr/bin/jackson"
else
    wrapper jackson "$files/usr/bin/jackson"
fi
ln -sf jackson "$files/usr/bin/j"

if [ -f "$src/bin/jacksond" ]; then
    install -m 0755 "$src/bin/jacksond" "$files/usr/lib/svoya/jacksond"
else
    wrapper jackson.daemon "$files/usr/lib/svoya/jacksond"
fi

# the voice service runs with the voice module's venv (sos install voice)
install -m 0755 "$src/bin/svoya-voice" "$files/usr/lib/svoya/svoya-voice"

# jacksond.service: Documentation=file:///usr/share/doc/svoya-jackson/README.md
if [ -f "$src/README.md" ]; then
    install -D -m 0644 "$src/README.md" "$files/usr/share/doc/svoya-jackson/README.md"
fi

for skill in "$src"/skills/*/SKILL.md; do
    [ -f "$skill" ] || continue
    install -D -m 0644 "$skill" "$files/usr/share/svoya/jackson/skills/$(basename "$(dirname "$skill")")/SKILL.md"
done

units=$(find "$src/systemd" -maxdepth 1 -type f \( -name '*.service' -o -name '*.socket' -o -name '*.timer' \) 2>/dev/null || true)
if [ -n "$units" ]; then
    for u in $units; do install -m 0644 "$u" "$files/usr/lib/systemd/user/"; done
else
    cat >"$files/usr/lib/systemd/user/jacksond.service" <<'UNIT'
[Unit]
Description=Jackson, the SOS assistant
Documentation=https://github.com/svoya-os/sos
PartOf=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/lib/svoya/jacksond
Restart=on-failure
RestartSec=2

[Install]
WantedBy=graphical-session.target
UNIT
fi
