pragma Singleton

// Shell-level actions shared by the bar, launcher, IPC and keybinds: lock,
// screenshot, session, undo/doctor, layout presets, Hyprland preferences and
// the setup wizard. Nothing here asks questions; confirmation lives in the UI.

import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    signal lockRequested

    function lock() {
        root.lockRequested();
    }

    // ---- Jackson ---------------------------------------------------------------------
    function askJackson(text) {
        Ui.show("jackson");
        if (text && text.trim().length > 0)
            Jackson.ask(text);
    }

    // «Настроить Джексона»: right-click on the mascot, the control center, IPC `jackson customize`
    function customizeJackson() {
        Ui.show("customizer");
    }

    // control center → «Оформление» (theme, accent, login screen, Jackson)
    function openLook() {
        Ui.ccPage = "look";
        Ui.show("cc");
    }

    // ---- screenshot (Super+Shift+S): slurp a region, grim it, offer actions -------------
    function hexRgba(c, a) {
        const h = v => ("0" + Math.round(v * 255).toString(16)).slice(-2);
        return "#" + h(c.r) + h(c.g) + h(c.b) + h(a);
    }

    function screenshot() {
        if (!Sys.has["grim"] || !Sys.has["slurp"]) {
            Notifs.shellToast(Strings.screenshotTools, "", "scan-text");
            return;
        }
        Ui.hide();
        const file = Sys.runtimeDir + "/shots/shot-" + Date.now() + ".png";
        const script = 'g=$(slurp -d -w 1 -b "$2" -c "$3" -s "$4") || exit 1; mkdir -p "$(dirname "$1")"; exec grim -g "$g" "$1"';
        // neutral frame (DESIGN §11: a selection frame is `text`, never the accent)
        Sys.sh(script, [file, root.hexRgba(Theme.wall, 0.35), root.hexRgba(Theme.text, 0.9), root.hexRgba(Theme.text, 0.06)], function (code) {
            if (code === 0) {
                Ui.shotPath = file;
                Ui.show("shot");
            }
        });
    }

    // ---- session ------------------------------------------------------------------------
    function logout() {
        Sys.detachSh('command -v hyprshutdown >/dev/null 2>&1 && exec hyprshutdown; exec hyprctl dispatch exit');
    }

    function suspend() {
        if (Settings.lockOnSuspend)
            root.lock();
        suspendTimer.restart();
    }

    function reboot() {
        Sys.detach(["systemctl", "reboot"]);
    }

    function poweroff() {
        Sys.detach(["systemctl", "poweroff"]);
    }

    // give the lock surfaces a moment to cover every output first
    Timer {
        id: suspendTimer

        interval: 500
        onTriggered: Sys.detach(["systemctl", "suspend"])
    }

    // ---- system (interactive in a terminal: the CLI asks before changing anything) -----
    readonly property string sosScript: 'c=$(command -v sos || command -v svoya) || { echo "sos: not installed"; read -r _; exit 1; }; "$c" "$@"; echo; printf "%s" "$0"; read -r _'

    function undo() {
        Sys.terminal(["sh", "-c", root.sosScript, Strings.t("Enter — закрыть", "Enter — close"), "undo"]);
    }

    function doctor() {
        Sys.terminal(["sh", "-c", root.sosScript, Strings.t("Enter — закрыть", "Enter — close"), "doctor"]);
    }

    // ---- setup wizard (separate Quickshell config) ----------------------------------------
    // step: "accessibility" | "" (the whole wizard). If the wizard already runs,
    // it jumps to the step over IPC; otherwise it starts (single instance).
    function openSetup(step) {
        const dir = Quickshell.shellDir + "/setup";
        const s = step && step.length > 0 ? step : "all";
        Sys.detachSh('quickshell -p "$1" ipc call setup open "$2" >/dev/null 2>&1 || SVOYA_SETUP_ONLY="$2" exec quickshell -n -p "$1"', [dir, s]);
    }

    // ---- layout presets and Hyprland preferences --------------------------------------------
    // The shell owns ~/.config/hypr/svoya-shell.conf (sourced by hyprland.conf):
    // the preset name, animations (reduce motion) and a custom keyboard layout.
    readonly property string hyprDir: Sys.home + "/.config/hypr"

    function setLayout(preset) {
        Settings.layout = preset; // onLayoutChanged below rewrites the prefs and reloads
    }

    function hyprPrefsText() {
        const preset = ["clean", "classic", "hacker"].indexOf(Settings.layout) >= 0 ? Settings.layout : "clean";
        let t = "# Generated by the SOS Shell from ~/.config/svoya/shell.json. Do not edit:\n";
        t += "# change settings in the shell, put your own Hyprland lines into user.conf.\n";
        t += "$svoya_preset = " + preset + "\n";
        t += "$svoya_animations = " + (Settings.reduceMotion ? "0" : "1") + "\n";
        if (Settings.kbCustom) {
            const clean = v => (v || "").replace(/[^A-Za-z0-9_,:+().-]/g, "");
            const layouts = clean(Settings.kbLayouts) || "us";
            t += "$svoya_kb_layout = " + layouts + "\n";
            // one empty variant per layout, so a variant from /etc/default/keyboard never
            // lands on a different layout
            t += "$svoya_kb_variant = " + ",".repeat(layouts.split(",").length - 1) + "\n";
            t += "$svoya_kb_options = " + clean(Settings.kbSwitch) + "\n";
        }
        return t;
    }

    property bool reloadAfterSave: false

    function syncHyprPrefs(reload) {
        const text = root.hyprPrefsText();
        if (hyprPrefs.text() === text) {
            if (reload)
                root.reloadHyprland();
            return;
        }
        root.reloadAfterSave = reload;
        hyprPrefs.setText(text);
    }

    function reloadHyprland() {
        if (Hypr.present)
            Sys.run(["hyprctl", "reload"]);
    }

    FileView {
        id: hyprPrefs

        path: root.hyprDir + "/svoya-shell.conf"
        printErrors: false
        onSaved: {
            if (root.reloadAfterSave)
                root.reloadHyprland();
            root.reloadAfterSave = false;
        }
    }

    Connections {
        target: Settings

        function onReduceMotionChanged() {
            root.syncHyprPrefs(true);
        }
        function onKbLayoutsChanged() {
            if (Settings.kbCustom)
                root.syncHyprPrefs(true);
        }
        function onKbSwitchChanged() {
            if (Settings.kbCustom)
                root.syncHyprPrefs(true);
        }
        function onLayoutChanged() {
            root.syncHyprPrefs(true);
        }
    }

    // First sync once Settings has loaded (no reload unless the file changed).
    Timer {
        interval: 2000
        running: true
        onTriggered: {
            const text = root.hyprPrefsText();
            if (hyprPrefs.text() !== text) {
                root.reloadAfterSave = true;
                hyprPrefs.setText(text);
            }
        }
    }
}
