# SPDX-License-Identifier: Apache-2.0
# Canonical's signed GRUB reads its configuration from \EFI\ubuntu, so the EFI directory keeps that
# name; the firmware boot entry is renamed to "SOS" and a Secure Boot capable fallback
# (shim as BOOTX64.EFI) is installed by contextualprocess@sos-after-bootloader.
---
efiBootLoader: "grub"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "ubuntu"
installEFIFallback: false
