# SPDX-License-Identifier: Apache-2.0
# Runs only when the user ticked "log in automatically" (users module sets autoLoginUser).
---
dontChroot: true
timeout: 30
autoLoginUser:
    "*": "/usr/lib/svoya/installer/autologin.sh ${ROOT} ${gs[autoLoginUser]}"
