# SPDX-License-Identifier: Apache-2.0
# Boot loader platform packages from the medium's pool: signed shim + GRUB (UEFI) or grub-pc (BIOS).
---
dontChroot: true
timeout: 1800
firmwareType:
    efi: "/usr/lib/svoya/installer/bootloader-packages.sh ${ROOT} efi"
    bios: "/usr/lib/svoya/installer/bootloader-packages.sh ${ROOT} bios"
