# SPDX-License-Identifier: Apache-2.0
# UEFI: firmware entry "SOS", Secure Boot capable fallback (\EFI\BOOT\BOOTX64.EFI = shim).
# BIOS: remember the boot disk for future grub-pc upgrades. Failures here never abort the install.
---
dontChroot: true
timeout: 300
firmwareType:
    efi: "-/usr/lib/svoya/installer/after-bootloader.sh ${ROOT} efi"
    bios: "-/usr/lib/svoya/installer/after-bootloader.sh ${ROOT} bios"
