# SPDX-License-Identifier: Apache-2.0
# Settings go to /etc/default/grub.d/ (next to svoya-base's 50-svoya.cfg); dracut is detected,
# so encrypted roots get rd.luks.uuid=.
---
overwrite: false
prefer_grub_d: true
keep_distributor: false
kernel_params: [ "quiet", "splash" ]
