# SPDX-License-Identifier: Apache-2.0
# Writes /etc/default/keyboard; the SOS session turns it into Hyprland's input settings at login.
---
xOrgConfFileName: "/etc/X11/xorg.conf.d/00-keyboard.conf"
convertedKeymapPath: "/lib/kbd/keymaps/xkb"
writeEtcDefaultKeyboard: true
configure:
    kwin: false
