# SPDX-License-Identifier: Apache-2.0
# No GeoIP lookup (no network call without the user asking); the map starts on Europe/Berlin.
---
region: "Europe"
zone: "Berlin"
localeGenPath: "/etc/locale.gen"
