# SPDX-License-Identifier: Apache-2.0
# Bind the installation medium into the target and point a private APT configuration at its pool.
---
dontChroot: true
timeout: 600
verbose: true
script:
    - "/usr/lib/svoya/installer/target-prepare.sh ${ROOT}"
i18n:
    name: "Preparing packages from the installation medium"
    name[ru]: "Подготовка пакетов с установочного носителя"
