# SPDX-License-Identifier: Apache-2.0
# The live system boots with casper/initramfs-tools; the installed system uses dracut.
---
dontChroot: true
timeout: 1800
verbose: true
script:
    - "/usr/lib/svoya/installer/dracut-swap.sh ${ROOT}"
i18n:
    name: "Setting up the boot image (dracut)"
    name[ru]: "Подготовка загрузочного образа (dracut)"
