# SPDX-License-Identifier: Apache-2.0
# NVIDIA: signed prebuilt driver from the medium's pool (no DKMS, no key enrollment);
# ubuntu-drivers if the pool has no matching branch and the machine is online.
---
dontChroot: true
timeout: 3600
verbose: true
script:
    - "/usr/lib/svoya/installer/gpu-drivers.sh ${ROOT}"
i18n:
    name: "Installing graphics drivers"
    name[ru]: "Установка драйверов видеокарты"
