# SPDX-License-Identifier: Apache-2.0
# The medium is bind-mounted at /run/sos-installer/medium by /usr/lib/svoya/installer/launch
# (it also finds the medium after a "toram" boot). Live-only files are never copied.
---
unpack:
    -   source: "/run/sos-installer/medium/casper/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""
        excludeFile: "/usr/share/svoya/live-exclude.rsync"
