[Appearance]
color_scheme_path={{ path.config }}/qt6ct/colors/svoya.conf
custom_palette=true
icon_theme={{ icons }}
standard_dialogs=xdgdesktopportal
style=Fusion

[Fonts]
fixed="{{ font.mono }},10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="{{ font.sans }},10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
