#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Stage cli/ + modules/ + themes/ into the layout of ARCHITECTURE §3:
#   cli/svoya_cli       -> /usr/lib/svoya/svoya_cli
#   cli/bin/sos|svoya   -> /usr/bin/sos, /usr/bin/svoya -> sos
#   modules/            -> /usr/share/svoya/modules
#   themes/*.toml       -> /usr/share/svoya/themes
#   themes/templates/   -> /usr/share/svoya/templates
#   cli/systemd/user/*  -> /usr/lib/systemd/user, cli/systemd/system/* -> /usr/lib/systemd/system
#   (loose unit files in cli/systemd are treated as user units)
set -euo pipefail
: "${SVOYA_SRC:?}" "${PKG_DIR:?}"
files=$PKG_DIR/files
mkdir -p "$files/usr/bin" "$files/usr/share/svoya/modules" "$files/usr/share/svoya/themes" \
    "$files/usr/share/svoya/templates"

python3 "$SVOYA_SRC/packages/lib/stage_pyapp.py" --src "$SVOYA_SRC/cli" --package svoya_cli --dest "$files" >/dev/null

entry=""
for cand in "$SVOYA_SRC/cli/bin/sos" "$SVOYA_SRC/cli/bin/svoya"; do
    if [ -f "$cand" ]; then entry=$cand; break; fi
done
if [ -n "$entry" ]; then
    install -m 0755 "$entry" "$files/usr/bin/sos"
else
    cat >"$files/usr/bin/sos" <<'PY'
#!/usr/bin/python3 -I
# Generated by packages/svoya-cli/prepare.sh. SPDX-License-Identifier: Apache-2.0
import sys

sys.path.insert(0, "/usr/lib/svoya")
from svoya_cli.main import main  # noqa: E402

sys.exit(main())
PY
fi
ln -sf sos "$files/usr/bin/svoya"

if [ -d "$SVOYA_SRC/modules" ]; then
    tar -C "$SVOYA_SRC/modules" --exclude='__pycache__' --exclude='*.pyc' --exclude='tests' \
        -cf - . | tar -C "$files/usr/share/svoya/modules" -xf -
fi
find "$SVOYA_SRC/themes" -maxdepth 1 -name '*.toml' -exec install -m 0644 -t "$files/usr/share/svoya/themes" {} +
if [ -d "$SVOYA_SRC/themes/templates" ]; then
    cp -a "$SVOYA_SRC/themes/templates/." "$files/usr/share/svoya/templates/"
fi

if [ -d "$SVOYA_SRC/cli/systemd" ]; then
    for kind in user system; do
        if [ -d "$SVOYA_SRC/cli/systemd/$kind" ]; then
            mkdir -p "$files/usr/lib/systemd/$kind"
            find "$SVOYA_SRC/cli/systemd/$kind" -maxdepth 1 -type f -exec install -m 0644 -t "$files/usr/lib/systemd/$kind" {} +
        fi
    done
    loose=$(find "$SVOYA_SRC/cli/systemd" -maxdepth 1 -type f \( -name '*.service' -o -name '*.timer' -o -name '*.socket' -o -name '*.path' \))
    if [ -n "$loose" ]; then
        mkdir -p "$files/usr/lib/systemd/user"
        for u in $loose; do install -m 0644 "$u" "$files/usr/lib/systemd/user/"; done
    fi
fi

# Shell completions for `sos` (and the `svoya` alias).
if [ -d "$SVOYA_SRC/cli/completions" ]; then
    c=$SVOYA_SRC/cli/completions
    if [ -f "$c/sos.bash" ]; then
        install -D -m 0644 "$c/sos.bash" "$files/usr/share/bash-completion/completions/sos"
        ln -sf sos "$files/usr/share/bash-completion/completions/svoya"
    fi
    if [ -f "$c/_sos" ]; then
        install -D -m 0644 "$c/_sos" "$files/usr/share/zsh/vendor-completions/_sos"
    fi
    if [ -f "$c/sos.fish" ]; then
        install -D -m 0644 "$c/sos.fish" "$files/usr/share/fish/vendor_completions.d/sos.fish"
    fi
fi

# Login-screen color helper + its polkit action (DESIGN §10, ARCHITECTURE §8).
install -D -m 0755 "$SVOYA_SRC/cli/libexec/theme-system-write" "$files/usr/lib/svoya/theme-system-write"
install -D -m 0644 "$SVOYA_SRC/cli/polkit/org.svoya.theme.policy" "$files/usr/share/polkit-1/actions/org.svoya.theme.policy"
