#!/usr/bin/env python3
"""SOS identity files: os-release, lsb-release, issue, issue.net, motd — generated from brand.py so the
version and names live in one place. Output goes to branding/os/root/… (paths as installed).

    python3 branding/os/generate.py

SPDX-License-Identifier: Apache-2.0
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "tools"))
import brand  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
REPO = "https://github.com/svoya-os/sos"
UBUNTU = {"release": "26.04", "codename": "resolute", "description": "Ubuntu 26.04 LTS"}
AMBER = brand.rgb(brand.color("graphite", "accent"))
PRETTY = f"{brand.NAME} {brand.VERSION} «{brand.CODENAME_RU}»"

OS_RELEASE = f"""# /usr/lib/os-release (with /etc/os-release → ../usr/lib/os-release) — SOS, Svoya Operating System.
# Generated by branding/os/generate.py. Spec: os-release(5).
NAME="{brand.NAME}"
PRETTY_NAME="{PRETTY}"
VERSION="{brand.VERSION} «{brand.CODENAME_RU}» ({brand.CODENAME_EN})"
VERSION_ID="{brand.VERSION}"
VERSION_CODENAME=signal
ID=sos
ID_LIKE="ubuntu debian"
UBUNTU_CODENAME={UBUNTU['codename']}
HOME_URL="{REPO}"
DOCUMENTATION_URL="{REPO}/tree/main/docs"
SUPPORT_URL="{REPO}/discussions"
BUG_REPORT_URL="{REPO}/issues"
PRIVACY_POLICY_URL="{REPO}/blob/main/docs/VISION.md#3-the-promise-published-binding"
LOGO=sos
ANSI_COLOR="38;2;{AMBER[0]};{AMBER[1]};{AMBER[2]}"
"""

LSB_RELEASE = f"""DISTRIB_ID={brand.NAME}
DISTRIB_RELEASE={brand.VERSION}
DISTRIB_CODENAME=signal
DISTRIB_DESCRIPTION="{PRETTY}"
"""

UPSTREAM_LSB = f"""# The engine SOS is built on (Linux Mint convention: /etc/upstream-release/lsb-release).
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE={UBUNTU['release']}
DISTRIB_CODENAME={UBUNTU['codename']}
DISTRIB_DESCRIPTION="{UBUNTU['description']}"
"""

# agetty(8) expands \S{…} from os-release, \n host, \l tty, \e{…} colors; the mark is drawn in the
# os-release ANSI_COLOR so a single value changes both. The console font needs · and — (Uni2 or Terminus).
ISSUE = """\\e[\\S{ANSI_COLOR}m··· ——— ···\\e[0m  \\S{PRETTY_NAME}
\\e{halfbright}\\n · \\l · \\r\\e{reset}

"""

ISSUE_NET = f"""{brand.NAME} {brand.VERSION}
"""

MOTD = f"""
  ··· ——— ···  {PRETTY}
  {brand.TAGLINE_RU} · {brand.TAGLINE_EN}

  svoya doctor     проверить GPU, драйвер и CUDA        check GPU, driver and CUDA
  svoya modules    добавить или убрать модули           add or remove modules
  svoya undo       откатить последнее изменение         undo the last change
  Super + J        Джексон · Jackson

  {REPO}

"""


def main() -> None:
    files = {
        "usr/lib/os-release": OS_RELEASE,
        "etc/lsb-release": LSB_RELEASE,
        "etc/upstream-release/lsb-release": UPSTREAM_LSB,
        "etc/issue": ISSUE,
        "etc/issue.net": ISSUE_NET,
        "etc/motd": MOTD,
    }
    for rel_path, text in files.items():
        p = brand.write(HERE / "root" / rel_path, text)
        print(brand.rel(p))


if __name__ == "__main__":
    main()
