"""NVIDIA device ID → architecture → driver branch / CUDA / PyTorch backend.

Facts (2026-09): R595 is the production branch for Turing and newer; Blackwell (RTX 50) needs the
open kernel modules. R580 is the last branch for Maxwell/Pascal/Volta (legacy). CUDA 13.x needs
driver ≥ 580 *and* Turing+; older GPUs stay on CUDA 12.x (PyTorch ``cu126`` wheels).
``uv --torch-backend=auto`` ignores the GPU generation (uv #14742), so svoya decides itself.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

# Generated by cli/tools/gen_nvidia_arch.py from pci.ids (github.com/pciutils/pciids, 2026-09).
ARCH_RANGES: tuple[tuple[int, int, str], ...] = (
    (0x06c0, 0x0e09, 'fermi'),
    (0x0e0a, 0x0e0b, 'kepler'),
    (0x0e0c, 0x0e0c, 'fermi'),
    (0x0e0f, 0x0e1b, 'kepler'),
    (0x0e22, 0x0f06, 'fermi'),
    (0x0fa0, 0x0fa7, 'kepler'),
    (0x0fb0, 0x0fb0, 'maxwell'),
    (0x0fb8, 0x0fb9, 'pascal'),
    (0x0fba, 0x0fbc, 'maxwell'),
    (0x0fc0, 0x103f, 'kepler'),
    (0x1040, 0x109b, 'fermi'),
    (0x10ef, 0x10f1, 'pascal'),
    (0x10f7, 0x10f9, 'turing'),
    (0x1140, 0x1140, 'fermi'),
    (0x1180, 0x11ff, 'kepler'),
    (0x1200, 0x1251, 'fermi'),
    (0x1280, 0x130b, 'kepler'),
    (0x1340, 0x1436, 'maxwell'),
    (0x15c2, 0x15ff, 'pascal'),
    (0x1613, 0x1676, 'maxwell'),
    (0x1725, 0x172f, 'pascal'),
    (0x174d, 0x17fd, 'maxwell'),
    (0x1ad6, 0x1aed, 'turing'),
    (0x1aef, 0x1af1, 'ampere'),
    (0x1b00, 0x1d56, 'pascal'),
    (0x1d81, 0x1df6, 'volta'),
    (0x1e02, 0x1ff9, 'turing'),
    (0x2080, 0x20ff, 'ampere'),
    (0x2182, 0x21d1, 'turing'),
    (0x2200, 0x2291, 'ampere'),
    (0x22a3, 0x22a3, 'hopper'),
    (0x22ba, 0x22be, 'ada'),
    (0x22ce, 0x22ec, 'blackwell'),
    (0x2302, 0x23f0, 'hopper'),
    (0x2414, 0x25fb, 'ampere'),
    (0x2681, 0x28f8, 'ada'),
    (0x2900, 0x3400, 'blackwell'),
)

# A few well-known boards (for tests, docs and nicer names when lspci is old).
KNOWN: dict[int, str] = {
    0x1b06: "GeForce GTX 1080 Ti", 0x1b80: "GeForce GTX 1080", 0x1c03: "GeForce GTX 1060 6GB",
    0x1d81: "TITAN V", 0x1e04: "GeForce RTX 2080 Ti", 0x1f08: "GeForce RTX 2060",
    0x2184: "GeForce GTX 1660", 0x2204: "GeForce RTX 3090", 0x2487: "GeForce RTX 3060",
    0x2684: "GeForce RTX 4090", 0x2704: "GeForce RTX 4080", 0x2782: "GeForce RTX 4070 Ti",
    0x2803: "GeForce RTX 4060 Ti", 0x2b85: "GeForce RTX 5090", 0x2c02: "GeForce RTX 5080",
    0x2c05: "GeForce RTX 5070 Ti", 0x2f04: "GeForce RTX 5070", 0x2d04: "GeForce RTX 5060 Ti",
    0x2bb1: "RTX PRO 6000 Blackwell", 0x2330: "H100 SXM5 80GB", 0x20b5: "A100 PCIe 80GB",
    0x1eb8: "Tesla T4", 0x27b8: "L4",
}


@dataclass(frozen=True)
class ArchInfo:
    id: str
    name: str
    order: int
    cc: str                 # CUDA compute capability
    branch: str | None      # recommended driver branch in the archive (None: no supported driver)
    open_modules: str       # required | recommended | unsupported
    torch: str              # PyTorch wheel backend for uv (UV_TORCH_BACKEND)
    cuda: str               # newest CUDA major that supports the GPU
    legacy: bool


ARCH: dict[str, ArchInfo] = {a.id: a for a in (
    ArchInfo("fermi", "Fermi", 1, "2.x", None, "unsupported", "cpu", "—", True),
    ArchInfo("kepler", "Kepler", 2, "3.x", None, "unsupported", "cpu", "—", True),
    ArchInfo("maxwell", "Maxwell", 3, "5.x", "580", "unsupported", "cu126", "12.x", True),
    ArchInfo("pascal", "Pascal", 4, "6.x", "580", "unsupported", "cu126", "12.x", True),
    ArchInfo("volta", "Volta", 5, "7.0", "580", "unsupported", "cu126", "12.x", True),
    ArchInfo("turing", "Turing", 6, "7.5", "595", "recommended", "cu130", "13.x", False),
    ArchInfo("ampere", "Ampere", 7, "8.x", "595", "recommended", "cu130", "13.x", False),
    ArchInfo("ada", "Ada Lovelace", 8, "8.9", "595", "recommended", "cu130", "13.x", False),
    ArchInfo("hopper", "Hopper", 9, "9.0", "595", "recommended", "cu130", "13.x", False),
    ArchInfo("blackwell", "Blackwell", 10, "10.x/12.x", "595", "required", "cu130", "13.x", False),
)}

PRODUCTION_BRANCH = "595"
LEGACY_BRANCH = "580"
CUDA13_MIN_DRIVER = 580
BLACKWELL_MIN_DRIVER = 570

# Marketing-name fallback (lspci without IDs, nvidia-smi names, unknown new IDs). Order matters.
NAME_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"RTX\s*PRO\s*\d+.*Blackwell|RTX\s*50\d\d|\bB[123]00\b|\bGB\d{2,3}\b|DGX\s*Spark", "blackwell"),
    (r"RTX\s*40\d\d|RTX\s*\d+\s*Ada|\bL40S?\b|\bL4\b|\bAD10\d", "ada"),
    (r"\bH(100|200|800|20)\b|\bGH\d{3}", "hopper"),
    (r"RTX\s*30\d\d|RTX\s*A\d{3,4}\b|\bA(100|10G?|16|2|30|40|800)\b|\bGA10\d", "ampere"),
    (r"RTX\s*20\d\d|GTX\s*16\d\d|TITAN\s*RTX|Quadro\s*RTX|\bT(4|400|600|1000)\b|\bTU1\d\d", "turing"),
    (r"TITAN\s*V\b|V100|\bGV100", "volta"),
    (r"GTX\s*TITAN\s*X\b|GTX\s*9\d\d|GTX\s*750|Quadro\s*M\d+|\bM(40|60)\b|\bGM\d{3}", "maxwell"),
    (r"GTX\s*10\d\d|GT\s*10\d\d|TITAN\s*Xp?\b|P100|P40|\bP4\b|Quadro\s*P\d+|\bGP10\d", "pascal"),
    (r"GTX\s*[67]\d\d|GT\s*[67]\d\d|\bGK\d{3}|Tesla\s*K\d+", "kepler"),
)


def arch_from_id(device_id: int) -> str | None:
    for lo, hi, arch in ARCH_RANGES:
        if lo <= device_id <= hi:
            return arch
    return None


def arch_from_name(name: str) -> str | None:
    for pat, arch in NAME_PATTERNS:
        if re.search(pat, name or "", re.IGNORECASE):
            return arch
    return None


def arch_for(device_id: int | None, name: str | None = None) -> str | None:
    arch = arch_from_id(device_id) if device_id is not None else None
    return arch or arch_from_name(name or "")


def info(arch: str | None) -> ArchInfo | None:
    return ARCH.get(arch or "")


def driver_packages(branch: str, open_modules: bool, kernel_flavor: str = "generic") -> list[str]:
    """Canonical-signed prebuilt modules (Secure Boot works without MOK enrollment)."""
    sfx = "-open" if open_modules else ""
    return [f"nvidia-driver-{branch}{sfx}", f"linux-modules-nvidia-{branch}{sfx}-{kernel_flavor}"]


def kernel_flavor(release: str) -> str:
    """``6.17.0-9-generic`` → ``generic``; ``6.17.0-1004-lowlatency`` → ``lowlatency``."""
    m = re.match(r"^\d+\.\d+\.\d+-\d+-(.+)$", release or "")
    return m.group(1) if m else "generic"


def parse_version(v: str | None) -> tuple[int, ...]:
    if not v:
        return ()
    return tuple(int(x) for x in re.findall(r"\d+", v)[:3])
