#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Stage the identity files of svoya-base (os-release, lsb-release, issue, motd) into $PKG_DIR/files.
# Source of truth: branding/os/root/<installed path> (generated by branding/os/generate.py, see
# branding/os/README.md). A "<file>.in" there is a template: @VERSION@, @VERSION_ID@, @CODENAME_RU@,
# @CODENAME_EN@ and @UBUNTU_CODENAME@ are substituted. Without branding files, built-in defaults are
# written so the package still builds.
set -euo pipefail
: "${SVOYA_SRC:?}" "${PKG_DIR:?}"
# shellcheck source=image/config.env
. "$SVOYA_SRC/image/config.env"

files=$PKG_DIR/files
brand=$SVOYA_SRC/branding/os/root
mkdir -p "$files/usr/lib" "$files/etc/upstream-release"

render() { # PATH (as installed, e.g. usr/lib/os-release) DEFAULT-CONTENT
    local path=$1 default=$2 dest=$files/$1 tpl=""
    for cand in "$brand/$path.in" "$brand/$path"; do
        if [ -f "$cand" ]; then tpl=$cand; break; fi
    done
    mkdir -p "$(dirname "$dest")"
    if [ -n "$tpl" ]; then
        echo "    /$path from ${tpl#"$SVOYA_SRC"/}" >&2
        sed -e "s|@VERSION@|$SOS_VERSION «$SOS_CODENAME_RU»|g" \
            -e "s|@VERSION_ID@|$SOS_VERSION|g" \
            -e "s|@CODENAME_RU@|$SOS_CODENAME_RU|g" \
            -e "s|@CODENAME_EN@|$SOS_CODENAME_EN|g" \
            -e "s|@UBUNTU_CODENAME@|$SUITE|g" "$tpl" >"$dest"
    else
        echo "    /$path: branding file missing, using the built-in default" >&2
        printf '%s\n' "$default" >"$dest"
    fi
}

render usr/lib/os-release "NAME=\"SOS\"
PRETTY_NAME=\"SOS $SOS_VERSION «$SOS_CODENAME_RU»\"
VERSION=\"$SOS_VERSION «$SOS_CODENAME_RU»\"
VERSION_ID=\"$SOS_VERSION\"
VERSION_CODENAME=signal
ID=sos
ID_LIKE=\"ubuntu debian\"
UBUNTU_CODENAME=$SUITE
HOME_URL=\"https://github.com/svoya-os/sos\"
SUPPORT_URL=\"https://github.com/svoya-os/sos/discussions\"
BUG_REPORT_URL=\"https://github.com/svoya-os/sos/issues\"
PRIVACY_POLICY_URL=\"https://github.com/svoya-os/sos/blob/main/docs/VISION.md\"
LOGO=sos"

render etc/lsb-release "DISTRIB_ID=SOS
DISTRIB_RELEASE=$SOS_VERSION
DISTRIB_CODENAME=signal
DISTRIB_DESCRIPTION=\"SOS $SOS_VERSION «$SOS_CODENAME_RU»\""

render etc/issue "SOS $SOS_VERSION \\n \\l
"
render etc/issue.net "SOS $SOS_VERSION"

# The engine underneath, for tools that need to know (Linux Mint's convention).
render etc/upstream-release/lsb-release "DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=26.04
DISTRIB_CODENAME=$SUITE
DISTRIB_DESCRIPTION=\"Ubuntu 26.04 LTS\""

# branding/os/root/etc/motd is printed by /etc/update-motd.d/10-help-text (diverted from base-files)
# instead of being installed as /etc/motd: base-files' postinst (re)writes /etc/motd on configure,
# which would fight with a conffile of ours.
if [ -f "$brand/etc/motd" ]; then
    install -D -m 0644 "$brand/etc/motd" "$files/usr/share/svoya/motd"
fi

# Sanity: tools resolve the Ubuntu archive through UBUNTU_CODENAME (branding/os/README.md).
os=$files/usr/lib/os-release
grep -q '^ID=sos$' "$os" || { echo "os-release: ID=sos missing" >&2; exit 1; }
grep -q "^UBUNTU_CODENAME=$SUITE\$" "$os" ||
    { echo "os-release: UBUNTU_CODENAME is not $SUITE (branding/os/root/usr/lib/os-release)" >&2; exit 1; }
grep -q "^DISTRIB_CODENAME=$SUITE\$" "$files/etc/upstream-release/lsb-release" ||
    { echo "upstream-release/lsb-release: DISTRIB_CODENAME is not $SUITE" >&2; exit 1; }
