// generated by generate.py — do not edit
window.SVOYA_PLYMOUTH = {
 "geometry": {
  "FPS": 50,
  "LINE_FRAC": 0.62,
  "LINE_MAX": 1180,
  "LINE_Y_FRAC": 0.46,
  "FADE_FRAC": 0.2,
  "LINE_CORE": 7,
  "BURST_W": 265,
  "BURST_BASE": 29,
  "BURST_LEAD": 12,
  "BURST_TAIL": 64,
  "FLARE_PAD": 14,
  "FLARE_BASE": 29,
  "N_SYMBOLS": 9,
  "KEY_UNIT": 0.1,
  "KEY_PERIOD": 34,
  "BASE_OPACITY": 0.8,
  "BURST_REST": 0.78,
  "T_SPOT": 0.18,
  "T_HOLD": 0.16,
  "T_STRETCH": 0.42,
  "T_SETTLE": 0.3,
  "T_BURST": 0.26,
  "T_WORD": 0.4,
  "WORD_GAP": 58,
  "CAPTION_GAP": 14,
  "PROMPT_GAP": 54,
  "FIELD_W": 380,
  "BULLET_PITCH": 11,
  "MSG_BOTTOM": 64,
  "MSG_LINE": 22,
  "FONT_MONO": "IBM Plex Mono 13px",
  "FONT_MONO_SMALL": "IBM Plex Mono 12px"
 },
 "symbols": [
  [
   12,
   7,
   0,
   1
  ],
  [
   26,
   7,
   2,
   1
  ],
  [
   40,
   7,
   4,
   1
  ],
  [
   68,
   21,
   8,
   3
  ],
  [
   96,
   21,
   12,
   3
  ],
  [
   124,
   21,
   16,
   3
  ],
  [
   166,
   7,
   22,
   1
  ],
  [
   180,
   7,
   24,
   1
  ],
  [
   194,
   7,
   26,
   1
  ]
 ],
 "bg": [
  [
   15,
   16,
   18
  ],
  [
   11,
   12,
   14
  ]
 ],
 "text": [
  235,
  232,
  225
 ],
 "dim": [
  157,
  154,
  146
 ],
 "faint": [
  103,
  101,
  95
 ],
 "frames": [
  [
   "1-power-on",
   "0,10 с — точка",
   {
    "t": 0.1
   }
  ],
  [
   "2-warm-up",
   "0,52 с — точка растягивается в линию",
   {
    "t": 0.52
   }
  ],
  [
   "3-boot-24",
   "загрузка · 24 %",
   {
    "t": 1.93,
    "progress": 0.24
   }
  ],
  [
   "4-boot-71-message",
   "загрузка · 71 % · сообщение",
   {
    "t": 5.21,
    "progress": 0.71,
    "messages": [
     "Проверка файловой системы на /dev/nvme0n1p2 — 37 %"
    ]
   }
  ],
  [
   "5-unlock",
   "ключ диска (LUKS)",
   {
    "t": 7.64,
    "progress": 0.31,
    "password": 9,
    "prompt": "Please enter passphrase for disk Samsung SSD 990 PRO (luks-3f1c)"
   }
  ],
  [
   "6-shutdown",
   "выключение",
   {
    "t": 2.43,
    "mode": "shutdown"
   }
  ]
 ]
};
