# SOS installer (Calamares 3.3, Ubuntu 26.04 package). SPDX-License-Identifier: Apache-2.0
# Installed to /etc/calamares by svoya-installer; helper scripts live in /usr/lib/svoya/installer.
---
modules-search: [ local ]

instances:
- id: sos-prepare
  module: shellprocess
  config: shellprocess_sos-prepare.conf
- id: sos-bootloader-packages
  module: contextualprocess
  config: contextualprocess_sos-bootloader-packages.conf
- id: sos-dracut
  module: shellprocess
  config: shellprocess_sos-dracut.conf
- id: sos-gpu
  module: shellprocess
  config: shellprocess_sos-gpu.conf
- id: sos-after-bootloader
  module: contextualprocess
  config: contextualprocess_sos-after-bootloader.conf
- id: sos-autologin
  module: contextualprocess
  config: contextualprocess_sos-autologin.conf
- id: sos-finalize
  module: shellprocess
  config: shellprocess_sos-finalize.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - dracutlukscfg
  - users
  - networkcfg
  - hwclock
  - shellprocess@sos-prepare
  - contextualprocess@sos-bootloader-packages
  - shellprocess@sos-dracut
  - shellprocess@sos-gpu
  - grubcfg
  - bootloader
  - contextualprocess@sos-after-bootloader
  - contextualprocess@sos-autologin
  - shellprocess@sos-finalize
  - umount
- show:
  - finished

branding: svoya
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
